services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ppworld-backend
    ports:
      - "8090:8000"
    networks:
      - shared_proxy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ppworld-frontend
    ports:
      - "3090:3000"
    networks:
      - shared_proxy
    restart: unless-stopped

networks:
  shared_proxy:
    external: true
